
package Depreciacion;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author arturo-collado
 */
public class LineaRecta extends javax.swing.JInternalFrame {

    DefaultTableModel dm = new DefaultTableModel ();
    
    private JComboBox<String> Combobox;
  
   
   
   /** private DefaultTableModel dtm;
    private Object[] o = new Object[6];
    
     * Creates new form LineaRecta
     */
    public LineaRecta() {
        initComponents();
        
     
     
          
     
        
        
        String ids [] = {"Articulo", "Año", "Depreciacion Anual", "Depreciacion Acumulada", "Valor en Libros"};
        
        dm.setColumnIdentifiers(ids);
        
        jTable2.setModel(dm);
        /**dtm = (DefaultTableModel)TablaLineaRecta.getModel();*/
         
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        VidaUtil = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CostoInicial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ValorSalvamento = new javax.swing.JTextField();
        Calcular = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Articulo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Eliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Metodo de Linea Recta");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Articulo", "Años", "Depreciacion Anual", "Depreciacion Acumulada", "Valor en Libros"
            }
        ));
        jScrollPane1.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setHeaderValue("Articulo");
            jTable2.getColumnModel().getColumn(1).setHeaderValue("Años");
            jTable2.getColumnModel().getColumn(2).setHeaderValue("Depreciacion Anual");
            jTable2.getColumnModel().getColumn(3).setHeaderValue("Depreciacion Acumulada");
            jTable2.getColumnModel().getColumn(4).setHeaderValue("Valor en Libros");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 298, 1010, 289));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Depreciación por Linea Recta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 250, -1));

        jLabel2.setText("Años de vida util:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, 20));

        jLabel3.setText("Seleccione el activo a depreciar:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));
        getContentPane().add(VidaUtil, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 100, -1));

        jLabel4.setText("Introduzca los siguientes datos:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        jLabel5.setText("Costo inicial del activo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, 20));
        getContentPane().add(CostoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 100, -1));

        jLabel6.setText("Valor de Salvamento:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, 20));
        getContentPane().add(ValorSalvamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 100, -1));

        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });
        getContentPane().add(Calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Edificio", "10-30 Años"},
                {"Maquinaria", "5-10 Años"},
                {"Mobiliario y Equipo de Oficina", "5-10 Años"},
                {"Muebles y Enseres", "2-10 Años"},
                {"Equipo de Transporte", "3-8 Años"},
                {"Equipo de Entrega y Reparto", "3-8 Años"}
            },
            new String [] {
                "Activo Fijo", "Años de Depreciacion"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 310, 130));

        Articulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Edificio", "Maquinaria", "Mobiliario y Equipo de Oficina", "Muebles y Enseres", "Equipo de Transporte", "Equipo de Entrega y Reparto" }));
        Articulo.setSelectedItem(this);
        Articulo.setActionCommand("");
        Articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArticuloActionPerformed(evt);
            }
        });
        getContentPane().add(Articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 150, -1));

        jLabel7.setText("Activo Fijo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void operaciones (){
        
    }
  
    
    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
    
        
        String Art = String.valueOf(Articulo.getSelectedItem());
    int VidaU = Integer.valueOf(VidaUtil.getText());
    double ValorS = Double.parseDouble(ValorSalvamento.getText());
   double CostoI = Double.parseDouble(CostoInicial.getText());
     double DepAnual = (CostoI - ValorS ) / VidaU;
     
     for (int i = 0; i < VidaU; i++) {
                    double depreciacionAcumulada = DepAnual * (i + 1);
                    double valorEnLibros = CostoI - depreciacionAcumulada;

                    dm.addRow(new Object[]{
                            Art,
                            i + 1,
                            DepAnual,
                            depreciacionAcumulada,
                            valorEnLibros}); 
                    
                      }
            
        
    
     
     //int Año = VidaU - VidaU + 1; 
     
      
            
    //double DepAcum = DepAnual * Año;
    
    
            
   //double ValorL = CostoI - DepAcum;
    
     
       
     
     
     //dm.addRow(new Object[]{Art,Año,DepAnual,DepAcum,ValorL});
                            
     
     
        
        /*Esta parte basicamente es para la seleccion del combobox aunque no se si funcionara, 
        me parecio mejor y mas practico que los checkbox, pero no se mucho sobre la tabla, asi que les dejo esta parte.
        
        String seleccion = (String)Articulo.getSelectedItem();
        
        if(seleccion.equals ("Edificio") ){
            
            o[0] = Articulo.getModel().trim();
        }
        else if(seleccion.equals ("Maquinaria")){    
            
        }
        
        o[1] = VidaUtil.getText().trim();
        o[2] = DepreAnual.getText().trim();
        o[3] = DepreAcumulada.getText().trim();
        o[4] = txtUnit.getText().trim();
        o[5] = ValorL.getText().trim();
        
          dtm.addRow(o); */

    }//GEN-LAST:event_CalcularActionPerformed

    //JButton eliminarButton = new JButton("Eliminar");
//eliminarButton.addActionListener(new ActionListener() {
    
        
    
    private void ArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArticuloActionPerformed
        // TODO add your handling code here:
         String seleccion = Articulo.getSelectedItem().toString();
    }//GEN-LAST:event_ArticuloActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        // Eliminar la fila seleccionada de la tabla
        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow != -1) {
            dm.removeRow(selectedRow);
        } else {
            // Mostrar un mensaje si no se ha seleccionado ninguna fila
            JOptionPane.showMessageDialog(null, "Selecciona una fila para eliminar", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_EliminarActionPerformed
}  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Articulo;
    private javax.swing.JButton Calcular;
    private javax.swing.JTextField CostoInicial;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField ValorSalvamento;
    private javax.swing.JTextField VidaUtil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
