
package Depreciacion;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arturo-collado
 */
public class SumaDigitos extends javax.swing.JInternalFrame {

    DefaultTableModel dm = new DefaultTableModel ();
    
    private JComboBox<String> Combobox;
    
    /**
     * Creates new form SumaDigitos
     */
    public SumaDigitos() {
        initComponents();
        
        String ids [] = {"Articulo", "Año", "Valor en Libros", "Depreciacion Anual", "Depreciacion Acumulada" };
        
        dm.setColumnIdentifiers(ids);
        
        jTable2.setModel(dm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        VidaUtil = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CostoInicial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ValorSalvamento = new javax.swing.JTextField();
        Calcular = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Articulo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Eliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Metodo de la Suma de los Digitos del Año");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Depreciacion por Suma de Digitos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 290, -1));

        jLabel2.setText("Años de vida util:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, 20));

        jLabel3.setText("Seleccione el activo a depreciar:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));
        getContentPane().add(VidaUtil, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 100, -1));

        jLabel4.setText("Introduzca los siguientes datos:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel5.setText("Costo inicial del activo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, 20));
        getContentPane().add(CostoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 100, -1));

        jLabel6.setText("Valor de Salvamento:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, 20));
        getContentPane().add(ValorSalvamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 100, -1));

        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });
        getContentPane().add(Calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Edificio", "10-30 Años"},
                {"Maquinaria", "5-10 Años"},
                {"Mobiliario y Equipo de Oficina", "5-10 Años"},
                {"Muebles y Enseres", "2-10 Años"},
                {"Equipo de Transporte", "3-8 Años"},
                {"Equipo de Entrega y Reparto", "3-8 Años"}
            },
            new String [] {
                "Activo Fijo", "Años de Depreciacion"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 310, 130));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Articulo", "Años", "Valor en Libros", "Depreciacion Anual", "Depreciacion Acumulada"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 298, 960, 280));

        Articulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Edificio", "Maquinaria", "Mobiliario y Equipo de Oficina", "Muebles y Enseres", "Equipo de Transporte", "Equipo de Entrega y Reparto" }));
        getContentPane().add(Articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 150, -1));

        jLabel7.setText("Activo Fijo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
      
       String Art = String.valueOf(Articulo.getSelectedItem());
    int VidaU = Integer.valueOf(VidaUtil.getText());
    double ValorS = Double.parseDouble(ValorSalvamento.getText());
        double CostoI = Double.parseDouble(CostoInicial.getText());
        
    
    
    // Cálculo de depreciación por el método de suma de dígitos
                /**double TotalDepreciacion = VidaU * (VidaU + 1) / 2;
                for (int i = 0; i < VidaU; i++) {
                    double Factor = (VidaU- i) / TotalDepreciacion;
                    double DepreciacionAnual = (CostoI - ValorS) * Factor;
                    double DepreciacionAcumulada = DepreciacionAnual * (i + 1);
                    double ValorEnLibros = CostoI - DepreciacionAcumulada;

                    dm.addRow(new Object[]{
                            Art,
                            i + 1,
                            ValorEnLibros,
                            Factor,
                            DepreciacionAnual,
                            DepreciacionAcumulada,
                             }); */
                
                double TotalDepreciacion = (CostoI - ValorS);
        double DepreciacionSobrante = TotalDepreciacion;
        double DepreciacionAcum = 0;
                
                for (int Año = 1; Año <= VidaU; Año++) {
           
           
            double Depreciacion = (VidaU - Año + 1) * TotalDepreciacion * 2 / (VidaU * (VidaU + 1));
            DepreciacionAcum+= Depreciacion;
            double ValorLibros = CostoI - DepreciacionAcum;
        

            dm.addRow(new Object[]{
                            Art,
                            Año,
                            ValorLibros,
                            
                            Depreciacion,
                            DepreciacionAcum,
                             });
            }
    }//GEN-LAST:event_CalcularActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        // Eliminar la fila seleccionada de la tabla
        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow != -1) {
            dm.removeRow(selectedRow);
        } else {
            // Mostrar un mensaje si no se ha seleccionado ninguna fila
            JOptionPane.showMessageDialog(null, "Selecciona una fila para eliminar", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_EliminarActionPerformed
} 
                

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Articulo;
    private javax.swing.JButton Calcular;
    private javax.swing.JTextField CostoInicial;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField ValorSalvamento;
    private javax.swing.JTextField VidaUtil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
